[Pkg]
name = "Pkg.jl"
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
url = "https://pkgdocs.julialang.org/{version}/"
builds = []

[ChainRules]
name = "ChainRules.jl"
uuid = "082447d4-558c-5d27-93f4-14fc19e9eca2"
url =  "https://juliadiff.org/ChainRulesCore.jl/stable/"
builds = []

[ExprParsers]
name = "ExprParsers.jl"
url = "https://jolin-io.github.io/ExprParsers.jl/stable/"
builds = []

[Match]
name = "Match.jl"
uuid = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
url = "https://juliaservices.github.io/Match.jl/dev/"
builds = []

[Rematch2]
name = "Rematch2.jl"
url = "https://juliaservices.github.io/Rematch2.jl/stable/"
builds = []

[BinaryTraits]
name = "BinaryTraits.jl"
url = "https://tk3369.github.io/BinaryTraits.jl/stable/"
builds = []

[DynamicExpressions]
name = "DynamicExpressions.jl"
url = "https://symbolicml.org/DynamicExpressions.jl/stable/"
builds = []

[JuliaSyntax]
name = "JuliaSyntax.jl"
uuid = "70703baa-626e-46a2-a12c-08ffd08c73b4"
url = "https://julialang.github.io/JuliaSyntax.jl/dev/"
icon = {url = "https://julialang.org/assets/infra/julia.ico"}
builds = []

[Julog]
name = "Julog.jl"
url = "https://docs.juliahub.com/Julog/TpEtX/0.1.15/"
builds = []

[PrecompileTools]
name = "PrecompileTools.jl"
uuid = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
url = "https://julialang.github.io/PrecompileTools.jl/stable/"
icon = {url = "https://julialang.org/assets/infra/julia.ico"}
builds = []

[Comonicon]
name = "Comonicon.jl"
url = "https://comonicon.org/stable/"
builds = []

[Folds]
name = "Folds.jl"
uuid = "41a02a25-b8f0-4f67-bc48-60067656b558"
url = "https://juliafolds.github.io/Folds.jl/stable/"
builds = []

[JSServe]
name = "JSServe.jl"
url = "https://simondanisch.github.io/JSServe.jl/stable/"
builds = []

[Octavian]
name = "Octavian.jl"
url = "https://octavian.julialinearalgebra.org/stable/"
builds = []

[MLStyle]
name = "MLStyle.jl"
uuid = "d8e11817-5142-5d16-987a-aa16d5891078"
url = "https://thautwarm.github.io/MLStyle.jl/latest/"
icon = {url = "https://thautwarm.github.io/MLStyle.jl/latest/_static/favicon.ico"}
builds = []

[LoweredCodeUtils]
name = "LoweredCodeUtils.jl"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
url = "https://juliadebug.github.io/LoweredCodeUtils.jl/stable/"
builds = []

[Rocket]
name = "Rocket.jl"
url = "https://biaslab.github.io/Rocket.jl/stable/"
builds = []

[PikaParser]
name = "PikaParser.jl"
url = "https://lcsb-biocore.github.io/PikaParser.jl/stable/"
builds = []

[Transducers]
name = "Transducers.jl"
uuid = "28d57a85-8fef-5791-bfe6-a80928e7c999"
url = "https://juliafolds.github.io/Transducers.jl/stable/"
builds = []

[Automa]
name = "Automa.jl"
uuid = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
url = "https://biojulia.dev/Automa.jl/stable"
builds = []

[KernelAbstractions]
name = "KernelAbstractions.jl"
uuid = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
url = "https://juliagpu.github.io/KernelAbstractions.jl/stable/"
builds = []

[Finch]
name = "Finch.jl"
url = "http://willowahrens.io/Finch.jl/stable/"
icon = {url = "http://willowahrens.io/Finch.jl/stable/assets/favicon.ico"}
builds = []

[ExprTools]
name = "ExprTools.jl"
uuid = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
url = "https://invenia.github.io/ExprTools.jl/stable/"
builds = []

[Polyester]
name = "Polyester.jl"
url = "https://juliasimd.github.io/Polyester.jl/stable/"
builds = []

[LoopVectorization]
name = "LoopVectorization.jl"
url = "https://juliasimd.github.io/LoopVectorization.jl/stable/"
builds = []

[ArrayInterface]
name = "ArrayInterface.jl"
url = "https://docs.sciml.ai/ArrayInterface/stable/"
builds = []

[Cassette]
name = "Cassette.jl"
url = "https://julia.mit.edu/Cassette.jl/stable/"
icon = {file = "icons/Cassette.ico"}
builds = []

[BlockArrays]
name = "BlockArrays.jl"
url = "https://juliaarrays.github.io/BlockArrays.jl/stable/"
builds = []

[PAPI]
name = "PAPI.jl"
url = "https://juliaperf.github.io/PAPI.jl/stable/"
builds = []

[TensorKit]
name = "TensorKit.jl"
url = "https://jutho.github.io/TensorKit.jl/stable/"
icon = {file = "icons/TensorKit.ico"}
builds = []

[ResumableFunctions]
name = "ResumableFunctions.jl"
url = "https://juliadynamics.github.io/ResumableFunctions.jl/stable/"
builds = []

[TensorOperations]
name = "TensorOperations.jl"
url = "https://jutho.github.io/TensorOperations.jl/stable/"
icon = {file = "icons/TensorOperations.ico"}
builds = []

[Dagger]
name = "Dagger.jl"
url = "https://juliaparallel.org/Dagger.jl/stable/"
builds = []

[StaticArrays]
name = "StaticArrays.jl"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
url = "https://juliaarrays.github.io/StaticArrays.jl/stable/"
builds = []

[NNlib]
name = "NNlib.jl"
uuid = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
url = "https://fluxml.ai/NNlib.jl/{version}/"
icon = {url = "https://fluxml.ai/assets/favicon_io/favicon.ico"}
builds = []

[Functors]
name = "Functors.jl"
uuid = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
url = "https://fluxml.ai/Functors.jl/{version}/"
icon = {url = "https://fluxml.ai/assets/favicon_io/favicon.ico"}
builds = []

[Optimisers]
name = "Optimisers.jl"
uuid = "3bd65402-5787-11e9-1adc-39752487f4e2"
url = "https://fluxml.ai/Optimisers.jl/dev/"
icon = {url = "https://fluxml.ai/assets/favicon_io/favicon.ico"}
builds = []

[PropCheck]
name = "PropCheck.jl"
url = "https://seelengrab.github.io/PropCheck.jl/stable/"
builds = []

[MacroTools]
name = "MacroTools.jl"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
url = "http://fluxml.ai/MacroTools.jl/{version}/"
icon = {url = "https://fluxml.ai/assets/favicon_io/favicon.ico"}
builds = []

[Zygote]
name = "Zygote.jl"
uuid = "e88e6eb3-aa80-5325-afca-941959d7151f"
url = "https://fluxml.ai/Zygote.jl/{version}/"
icon = {file = "icons/Zygote.ico"}
builds = []

[IRTools]
name = "IRTools.jl"
uuid = "7869d1d1-7146-5819-86e3-90919afe41df"
url = "http://fluxml.ai/IRTools.jl/{version}/"
icon = {url = "https://fluxml.ai/assets/favicon_io/favicon.ico"}
builds = []

[OMEinsum]
name = "OMEinsum.jl"
uuid = "ebe7aa44-baf0-506c-a96f-8464559b3922"
url = "https://under-peter.github.io/OMEinsum.jl/{version}/"
builds = []

[Metal]
name = "Metal.jl"
uuid = "dde4c033-4e86-420c-a63e-0dd931031962"
url = "https://metal.juliagpu.org/stable/"
builds = []

[Flux]
name = "Flux.jl"
uuid = "587475ba-b771-5e3f-ad9e-33799f191a9c"
url = "https://fluxml.ai/Flux.jl/stable/"
icon = {url = "https://fluxml.ai/assets/favicon_io/favicon.ico"}
builds = []

[DataFrames]
name = "DataFrames.jl"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
url = "https://dataframes.juliadata.org/v1.6.1/"
icon = {url = "https://dataframes.juliadata.org/stable/assets/favicon.ico"}

[Tenet]
name = "Tenet.jl"
uuid = "85d41934-b9cd-44e1-8730-56d86f15f3ec"
registry = "bsc-quantic/Registry"
url = "https://bsc-quantic.github.io/Tenet.jl/stable/"

[EinExprs]
name = "EinExprs.jl"
uuid = "b1794770-133b-4de1-afb4-526377e9f4c5"
registry = "bsc-quantic/Registry"
url = "https://bsc-quantic.github.io/EinExprs.jl/stable/"
