name: Update DocSets
on:
  workflow_dispatch:
jobs:
  query-registry:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - id: setup-matrix
      run: python check-package-versions.py -o $GITHUB_OUTPUT
  generate-docset:
    needs: query-registry
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.query-registry.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python generate-docset.py ${{ matrix.bundle_id }} ${{ matrix.bundle_name }} ${{ matrix.platform_family }} ${{ matrix.url }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.bundle_name }}.docset
          path: ${{ matrix.bundle_name }}.docset
